version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - err113
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - usetesting
    - testpackage
    - thelper
    - unconvert
    - wastedassign
    - whitespace
    - wsl_v5
    - govet

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment # @todo fix later

    gosec:
      excludes: [G501, G502, G503, G504, G505] # ignore imports, usages are still reported

    revive:
      confidence: 0.8
      severity: error
      rules:
        - name: atomic
        - name: bare-return
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: confusing-naming
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        - name: datarace
        - name: deep-exit
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: flag-parameter
        - name: get-return
        - name: identical-branches
        - name: if-return
        - name: import-shadowing
        - name: increment-decrement
        - name: indent-error-flow
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: range
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: string-of-int
        - name: struct-tag
        - name: superfluous-else
        - name: time-equal
        - name: time-naming
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unnecessary-stmt
        - name: unused-parameter
        - name: unused-receiver
        - name: use-any
        - name: useless-break
        - name: var-declaration
        - name: waitgroup-by-value

    lll:
      tab-width: 4

    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      disable:
        - decl

  exclusions:
    paths:
      - mocks
    rules:
      # ignore unchecked errors, missing Close(), code complexity, constant enforcement, global variables,
      # line lengths and code duplicity in tests
      - path: _test\.go
        linters:
          - errcheck
          - bodyclose
          - cyclop
          - gocognit
          - goconst
          - gochecknoglobals
          - lll
          - dupl

      # ignore control flags in tests
      - path: _test\.go
        text: seems to be a control flag, avoid control coupling
        linters: [revive]

      # ignore unchecked errors in defer statements
      - source: "^\t+defer "
        linters: [errcheck]

      # ignore cuddle in tests
      - path: _test\.go
        text: only one cuddle assignment allowed before defer statement
        linters: [wsl_v5]

      # ignore expressions after assignment in tests
      - path: _test\.go
        text: only cuddled expressions if assigning variable or using from line above
        linters: [wsl_v5]

      # ignore expressions and assignments cuddling in tests
      - path: _test\.go
        text: assignments should only be cuddled with other assignments
        linters: [wsl_v5]

      # ignore err113 dynamic errors definition error...not sure how to approach this correctly now
      - text: do not define dynamic errors, use wrapped static errors instead
        linters: [err113]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(gitlab.cdn77.eu)

